# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# send to fully-virtualized infrastructure: https://docs.travis-ci.com/user/reference/xenial/
sudo: required
dist: xenial

cache:
  # default timeout is too low
  timeout: 600
  directories:
  - $HOME/.m2
  - $HOME/flink_cache
  # keep in sync with tools/travis/setup_maven.sh
  - $HOME/maven_cache
  # keep in sync with tools/travis/docs.sh
  - $HOME/gem_cache

# do not cache our own artifacts
before_cache:
  - rm -rf $HOME/.m2/repository/org/apache/flink/

install: true

language: java

git:
  depth: 100

env:
  global:
    # Global variable to avoid hanging travis builds when downloading cache archives.
    - MALLOC_ARENA_MAX=2
    - DOCKER_COMPOSE_VERSION=1.22.0
    - CHANGE_MINIKUBE_NONE_USER=true

before_script:
   - "export -f travis_nanoseconds"
   - "export -f travis_time_start"
   - "export -f travis_time_finish"

# Install maven 3.2.5 since xenial uses 3.3.9 for which shading is broken
before_install:
   - source ./tools/travis/setup_maven.sh

notifications:
  slack:
    rooms:
      - secure: ikPQn5JTpkyzxVyOPm/jIl3FPm6hY8xAdG4pSwxGWjBqF+NmmNTp9YZsJ6fD8xPql6T5n1hNDbZSC14jVUw/vvXGvibDXLN+06f25ZQl+4LJBXaiR7gTG6y3nO8G90Vw7XpvCme6n5Md9tvjygb17a4FEgRJFfwzWnnyPA1yvK0=
    on_success: never
    on_pull_requests: false
  webhooks:
    urls:
      secure: gOR0ayYgTHvx2QsFxxH07KzI8fgrDk2vqp/6q2eN/RuWHJa6kHecXz/9F0JOXNI1siXrSJ1FwCKOxiMmTbnImJP4015L9VGMS++us6AYtnFp6SIRorRqA1QS5tHNrpBIM38ANxQvuPhFj8S6216BsonQOqBu9sp0jQCOZGKwBLg=
    on_success: change
    on_pull_requests: false

stages:
  - name: compile
  - name: test
  - name: E2E
    if: type = cron
  - name: cleanup

jdk: "openjdk8"
jobs:
  include:
    # main profile
    - if: type in (pull_request, push)
      stage: compile
      script: ./tools/travis_controller.sh compile
      env: PROFILE="-Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11"
      name: compile
    - if: type in (pull_request, push)
      stage: test
      script: ./tools/travis_controller.sh core
      env: PROFILE="-Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11"
      name: core
    - if: type in (pull_request, push)
      script: ./tools/travis_controller.sh python
      env: PROFILE="-Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11"
      name: python
    - if: type in (pull_request, push)
      script: ./tools/travis_controller.sh libraries
      env: PROFILE="-Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11"
      name: libraries
    - if: type in (pull_request, push)
      script: ./tools/travis_controller.sh blink_planner
      env: PROFILE="-Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11"
      name: blink_planner
    - if: type in (pull_request, push)
      script: ./tools/travis_controller.sh connectors
      env: PROFILE="-Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11"
      name: connectors
    - if: type in (pull_request, push)
      script: ./tools/travis_controller.sh kafka/gelly
      env: PROFILE="-Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11"
      name: kafka/gelly
    - if: type in (pull_request, push)
      script: ./tools/travis_controller.sh tests
      env: PROFILE="-Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11"
      name: tests
    - if: type in (pull_request, push)
      script: ./tools/travis_controller.sh misc
      env: PROFILE="-Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11"
      name: misc
    - if: type in (pull_request, push)
      stage: cleanup
      script: ./tools/travis_controller.sh cleanup
      env: PROFILE="-Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11"
      name: cleanup
    # JDK11 profile
    - if: type = cron
      jdk: "openjdk11"
      stage: compile
      script: ./tools/travis_controller.sh compile
      env: PROFILE="-Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11 -Djdk11"
      name: compile - jdk 11
    - if: type = cron
      jdk: "openjdk11"
      stage: test
      script: ./tools/travis_controller.sh core
      env: PROFILE="-Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11 -Djdk11"
      name: core - jdk 11
    - if: type = cron
      jdk: "openjdk11"
      script: ./tools/travis_controller.sh connectors
      env: PROFILE="-Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11 -Djdk11"
      name: connectors - jdk 11
    - if: type = cron
      jdk: "openjdk11"
      stage: cleanup
      script: ./tools/travis_controller.sh cleanup
      env: PROFILE="-Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11 -Djdk11"
      name: cleanup - jdk 11
    # E2E profiles - Java 11
    - if: type = cron
      stage: test
      jdk: "openjdk11"
      env: PROFILE="-Djdk11 -Dinclude-hadoop -Dhadoop.version=2.8.3 -De2e-metrics"
      script: ./tools/travis/nightly.sh split_misc.sh
      name: e2e - misc - jdk11
